### PR TITLE
Add jekyll-seo-tag

### PR DESCRIPTION
**Pull request by pathawks**
I’m not sure I have added everything necessary.
On my phone now; I can squash when I get home tonight if you like.

### CODE REVIEW

**Comment by parkr** [comment]
LGTM, thank you!

**Comment by DirtyF** [comment]
@pathawks jekyllbot does not seem to be effective on the repo, anything else to do to activate it?

**Comment by parkr** [comment]
@DirtyF Which feature, specifically?

**Comment by DirtyF** [comment]
@parkr I tried to merge a PR like I usually do on jekyll and it did not merge it.

**Comment by pathawks** [comment]
@DirtyF Which PR?

It looks like you're not a member of @jekyll/plugin-core ; do you have write permissions on @jekyll/jekyll-seo-tag ?

**Comment by DirtyF** [comment]
@pathawks https://github.com/jekyll/jekyll-seo-tag/pull/189 but Ben merged it manually since. I see he is not using @jekyllbot either. I suggest you give it a try next time you want to merge a PR to see by yourself.

**Comment by pathawks** [comment]
It has [committed in the past](https://github.com/jekyll/jekyll-seo-tag/commits?author=jekyllbot)

**Pull request merged**
